name: continuous-integration

on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to JSR?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

env:
  RUSTFLAGS: ""

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          target: wasm32-unknown-unknown

      - name: Build WASM package
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Setup wasm-bindgen  
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen
      
      - name: Prepare WASM for Typescript
        run: wasm-bindgen target/wasm32-unknown-unknown/release/spreet_js_imports.wasm --out-dir imports --target deno

      - name: Do postbuild actions
        run: cargo run --bin postbuild

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.publish == 'true'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - run: npx jsr publish
